[tools]
lefthook = "latest"

[tasks.setup]
run = "lefthook install"

[tasks.test]
run = "swift test --parallel --enable-swift-testing"

[tasks.lint]
run = "swift format lint --recursive ."

[tasks.format]
run = "swift format --recursive --in-place ."

[tasks.start]
run = "swift run -c release aoc-2025"

[tasks.check]
depends = ["lint", "test"]
